### ISSUE TITLE
./harlanc test/hello.kfc took a very long time, is that normal?

### ISSUE THREAD

**Issue by muyinliu** [eholk/harlan#110]
@eholk I run the command "./harlanc test/hello.kfc" and it took over 2 minutes. But finally I got runnable file "hello". Is that normal? And why it took so long?

**Comment by eholk** [comment]
6e789cc0f997fd30c481958d7e54fa663eeb2cfa improves performance some more too. Compiling `hello.kfc` on my machine takes 8.5 seconds now. I'll continue to work on improving the compiler's performance, but I'm going to go ahead and consider this bug fixed.

Please let me know if you're still seeing multiple minute compile times though.
