### ISSUE TITLE
Start Help Needed

### ISSUE THREAD

**Issue by Stig9999** [eholk/harlan#144]
Hello.

When I try to use the 'make check' to make sure that everything works, I get an error as can be seen on the picture below.

![skaermbillede 2015-02-27 kl 13 51 49](https://cloud.githubusercontent.com/assets/11227219/6412773/7ed1b216-be88-11e4-9371-f74fda8a0482.png)

What am I doing wrong and how can I fix it? 
(and yes, im a bit new to all of this since its probably a "noob" question).

**Comment by eholk** [comment]
I saw you closed the issue. Does that mean you figured it out? If so, what was the fix?

**Comment by its2mc** [comment]
It seems like he did not run the make check form the cloned git repo itself as opposed to any other file location.

**Comment by Stig9999** [comment]
Yeah I didn't clone the files from github.

But now when Im trying to run the make check command, the result of the run shows the following: 
![skaermbillede 2015-03-02 kl 13 12 12](https://cloud.githubusercontent.com/assets/11227219/6440547/5ef1a46c-c0de-11e4-8b0e-0b538a4ba2a2.png)

And if I scroll up further in my terminal, to see where it failed it shows this:
![skaermbillede 2015-03-02 kl 13 14 05](https://cloud.githubusercontent.com/assets/11227219/6440577/9611a15e-c0de-11e4-8ef5-bf3a7a18cd8b.png)

Im not sure what that means, and how im suppose to fix that error. 

Can anyone help me out here?

**Comment by eholk** [comment]
If you fund `DEVICE=gpu make check`, do you get the same behavior?

This looks like an issue I've seen before that turned out to be a bug in
Apple's OpenCL implementation.

**Comment by Stig9999** [comment]
If i run the 'DEVICE=gpu make check', I get the same error and it tells me the same as the two pictures from my last post.

But if it is a bug with Apple's OpenCL implementation, how do I fix that?

**Comment by eholk** [comment]
I'm glad you figured it out!

As far as the bugs in Apple's OpenCL, the only thing we can do is wait for Apple to fix it. I've filed the bug with them and they check in with me each time a new version of OS X to see if it's fixed. On the bright side, very few Harlan programs trigger this bug, so in the meantime you can keep using Harlan and you probably won't run into the bug in the wild.

**Comment by eholk** [comment]
I'm closing this now because it looks like we had resolved this issue.
